version: "3.3"

x-common-extra-hosts: &extra-hosts
  # use host.docker.internal to access the host machine from within the container
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  backend:
    <<: [*extra-hosts]
    build:
      context: .
      dockerfile: ./Dockerfile
    image: d-gui-manager-web
    container_name: d-gui-manager-web
    entrypoint: /src/docker-entrypoint.sh
    ports:
      - "8000:8000"
    # attach docker sock to interact with the host docker
    volumes: 
      - ./src:/src
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
  
  redis:
    image: redis:alpine
    container_name: d-gui-manager-redis

  nvidia-cuda:
    image: nvidia/cuda:11.0.3-base-ubuntu20.04
    container_name: d-gui-cuda
    entrypoint: ["echo", "CUDA image ready"]
